[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "/entrypoint.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
NEXTAUTH_URL = "https://${{RAILWAY_PUBLIC_DOMAIN}}"
NEXTAUTH_SECRET = "${{AUTH_SECRET}}"
POSTBASE_JWT_SECRET = "${{AUTH_SECRET}}"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
