/**
 * OAuth 2.0 Authorization endpoint (PKCE flow).
 * URL: GET /api/auth/v1/{projectId}/oauth/authorize
 *
 * Query params:
 *   provider        - e.g. "github", "google"
 *   code_challenge  - PKCE code challenge (SHA-256, base64url encoded)
 *   state           - random opaque string generated by the client
 *   redirect_to     - URL on the customer app to redirect to after auth
 *
 * The endpoint:
 *   1. Validates the project + provider
 *   2. Builds the upstream OAuth authorization URL (e.g. GitHub)
 *   3. Redirects the browser to that URL
 *
 * No CSRF cookies needed — security comes from PKCE + state parameter.
 */
import { type NextRequest } from "next/server";
import { getEnabledProviders } from "@/lib/auth/config";
import { validateApiKey } from "@/lib/auth/keys";
import { db } from "@/lib/db";
import { projects } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import { getBaseUrl } from "@/lib/get-base-url";

// Map provider names to their OAuth authorization URLs
const PROVIDER_AUTH_URLS: Record<string, string> = {
  github: "https://github.com/login/oauth/authorize",
  google: "https://accounts.google.com/o/oauth2/v2/auth",
  discord: "https://discord.com/api/oauth2/authorize",
  twitter: "https://twitter.com/i/oauth2/authorize",
  facebook: "https://www.facebook.com/v19.0/dialog/oauth",
  linkedin: "https://www.linkedin.com/oauth/v2/authorization",
  gitlab: "https://gitlab.com/oauth/authorize",
  twitch: "https://id.twitch.tv/oauth2/authorize",
  spotify: "https://accounts.spotify.com/authorize",
};

// Default scopes per provider
const PROVIDER_DEFAULT_SCOPES: Record<string, string> = {
  github: "read:user user:email",
  google: "openid email profile",
  discord: "identify email",
  twitter: "tweet.read users.read offline.access",
  facebook: "email public_profile",
  linkedin: "openid profile email",
  gitlab: "read_user email",
  twitch: "user:read:email",
  spotify: "user-read-email user-read-private",
};

export async function GET(
  req: NextRequest,
  context: { params: Promise<{ projectId: string }> }
) {
  const { projectId } = await context.params;
  const { searchParams } = req.nextUrl;

  const provider = searchParams.get("provider");
  const codeChallenge = searchParams.get("code_challenge");
  const state = searchParams.get("state");
  const redirectTo = searchParams.get("redirect_to") ?? "";

  // Validate required params
  if (!provider || !codeChallenge || !state) {
    return Response.json(
      { error: "Missing required params: provider, code_challenge, state" },
      { status: 400 }
    );
  }

  // Validate API key
  const authHeader = req.headers.get("authorization");
  if (authHeader?.startsWith("Bearer ")) {
    const keyInfo = await validateApiKey(authHeader.slice(7), projectId);
    if (!keyInfo) {
      return Response.json({ error: "Invalid API key" }, { status: 401 });
    }
  }

  // Validate project
  const [project] = await db
    .select()
    .from(projects)
    .where(eq(projects.id, projectId))
    .limit(1);

  if (!project) {
    return Response.json({ error: "Project not found" }, { status: 404 });
  }

  // Validate provider is enabled + get client credentials
  const enabledProviders = await getEnabledProviders(projectId);
  const providerConfig = enabledProviders.find((p) => p.provider === provider);

  if (!providerConfig) {
    return Response.json(
      { error: `Provider '${provider}' is not enabled for this project` },
      { status: 400 }
    );
  }

  const { clientId } = providerConfig;
  if (!clientId) {
    return Response.json(
      { error: `Provider '${provider}' is missing client_id configuration` },
      { status: 500 }
    );
  }

  const providerAuthUrl = PROVIDER_AUTH_URLS[provider];
  if (!providerAuthUrl) {
    return Response.json(
      { error: `Provider '${provider}' does not support PKCE OAuth initiation` },
      { status: 400 }
    );
  }

  // The callback always lands on postbase — we encode redirect_to inside state
  const callbackUrl = `${getBaseUrl()}/api/auth/v1/${projectId}/oauth/callback/${provider}`;

  // Encode redirect_to inside state so we can extract it after callback
  // Format: <random_state>|<base64url(redirect_to)>
  const encodedRedirectTo = Buffer.from(redirectTo).toString("base64url");
  const fullState = `${state}|${encodedRedirectTo}`;

  // Build the upstream OAuth URL
  // NOTE: We do NOT forward code_challenge to the provider — the token exchange
  // happens server-side (we own both authorize + callback), so PKCE with the
  // upstream provider is unnecessary and would require forwarding code_verifier
  // too. The code_challenge generated by postbasejs is used only for our own
  // state validation, not passed upstream.
  const authUrl = new URL(providerAuthUrl);
  authUrl.searchParams.set("client_id", clientId);
  authUrl.searchParams.set("redirect_uri", callbackUrl);
  authUrl.searchParams.set("response_type", "code");
  authUrl.searchParams.set("state", fullState);

  const scopes = searchParams.get("scopes") ?? PROVIDER_DEFAULT_SCOPES[provider] ?? "";
  if (scopes) authUrl.searchParams.set("scope", scopes);

  // Provider-specific extras
  if (provider === "google") {
    authUrl.searchParams.set("access_type", "offline");
    authUrl.searchParams.set("prompt", "consent");
  }

  return new Response(null, {
    status: 302,
    headers: { location: authUrl.toString() },
  });
}
